name = "TBS-Server"
author = "Slash"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "131e2360fb704be45f9cd4bab0b287ebe0fb856550414593a3e918e0c971f47e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
