name = "TBS-Server"
author = "Slash"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6f4f381cf07d1c6bd07fb8004ef957b8c41ad3839234bdc7b56845bd3e342c9"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
