name = "TBS-Server"
author = "Slash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65d3bd9ea28c0d83cd0640f21f98ea47b3cd60cb5a0cfac9c09e568b0b4cc397"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
